=== Pringlez/ACCServerManager/service/src/test/resources/schemas/event-rules/getEventRules.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "qualifyStandingType": {
      "type": "integer"
    },
    "superpoleMaxCar": {
      "type": "integer"
    },
    "pitWindowLengthSec": {
      "type": "integer"
    },
    "driverStintTimeSec": {
      "type": "integer"
    },
    "mandatoryPitstopCount": {
      "type": "integer"
    },
    "maxTotalDrivingTime": {
      "type": "integer"
    },
    "maxDriversCount": {
      "type": "integer"
    },
    "isRefuellingAllowedInRace": {
      "type": "boolean"
    },
    "isRefuellingTimeFixed": {
      "type": "boolean"
    },
    "isMandatoryPitstopRefuellingRequired": {
      "type": "boolean"
    },
    "isMandatoryPitstopTyreChangeRequired": {
      "type": "boolean"
    },
    "isMandatoryPitstopSwapDriverRequired": {
      "type": "boolean"
    },
    "tyreSetCount": {
      "type": "integer"
    }
  },
  "required": [
    "id",
    "qualifyStandingType",
    "superpoleMaxCar",
    "pitWindowLengthSec",
    "driverStintTimeSec",
    "mandatoryPitstopCount",
    "maxTotalDrivingTime",
    "maxDriversCount",
    "isRefuellingAllowedInRace",
    "isRefuellingTimeFixed",
    "isMandatoryPitstopRefuellingRequired",
    "isMandatoryPitstopTyreChangeRequired",
    "isMandatoryPitstopSwapDriverRequired",
    "tyreSetCount"
  ]
}

=== Pringlez/ACCServerManager/docs/docker/acc-server/configs/eventRules.json
{
  "id": "5d405fca-6df0-45ba-9fa3-c163e294be06",
  "qualifyStandingType": 1,
  "superpoleMaxCar": -1,
  "pitWindowLengthSec": -1,
  "driverStintTimeSec": -1,
  "mandatoryPitstopCount": 0,
  "maxTotalDrivingTime": -1,
  "maxDriversCount": 1,
  "isRefuellingAllowedInRace": true,
  "isRefuellingTimeFixed": false,
  "isMandatoryPitstopRefuellingRequired": false,
  "isMandatoryPitstopTyreChangeRequired": false,
  "isMandatoryPitstopSwapDriverRequired": false,
  "tyreSetCount": 50
}

=== Pringlez/ACCServerManager/service/src/test/resources/scaffolding/eventRules/createEventRules.json
{
  "id": "c3573fe9-bae6-4f9d-9961-f79925e5bb80",
  "qualifyStandingType": 1,
  "superpoleMaxCar": -1,
  "pitWindowLengthSec": -1,
  "driverStintTimeSec": -1,
  "mandatoryPitstopCount": 0,
  "maxTotalDrivingTime": -1,
  "maxDriversCount": 16,
  "isRefuellingAllowedInRace": true,
  "isRefuellingTimeFixed": false,
  "isMandatoryPitstopRefuellingRequired": false,
  "isMandatoryPitstopTyreChangeRequired": false,
  "isMandatoryPitstopSwapDriverRequired": false,
  "tyreSetCount": 50
}
